name: Terraform

on:
  push:
    branches: [ main ]
    paths:
      - 'aws/terraform/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'aws/terraform/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: aws/terraform/ec2-lab
        run: terraform init

      - name: Terraform Format check
        working-directory: aws/terraform/ec2-lab
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: aws/terraform/ec2-lab
        run: terraform validate

      - name: Terraform Plan
        working-directory: aws/terraform/ec2-lab
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        working-directory: aws/terraform/ec2-lab
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

